on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dailysharepricecontainerregistry.azurecr.io
        username: ${{ secrets.acr_dailysharepricecontainerregistry_username }}
        password: ${{ secrets.acr_dailysharepricecontainerregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t dailysharepricecontainerregistry.azurecr.io/dailysharepricecluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push dailysharepricecontainerregistry.azurecr.io/dailysharepricecluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dailysharepricecluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dailysharepricecluster91cf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dailysharepricecluster91cf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dailysharepricecluster91cf
        container-registry-url: dailysharepricecontainerregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_dailysharepricecontainerregistry_username }}
        container-registry-password: ${{ secrets.acr_dailysharepricecontainerregistry_password }}
        secret-name: dailyshareprdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dailysharepricecluster91cf
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          dailysharepricecontainerregistry.azurecr.io/dailysharepricecluster:${{ github.sha }}
        imagepullsecrets: |
          dailyshareprdockerauth
